import "../globals.css";

import React from "react";
import { redirect } from "next/navigation";

import useUser from "@/lib/useUser";
import { Toaster } from "@/components/atoms/Toast/toaster";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await useUser();
  const canAccess = false;

  if (user?.session?.access_token && canAccess) {
    redirect("/");
  }

  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
